## Numpy

### Numerical Python
- 고성능 수치 계산을 위한 라이브러리
- 벡터나 행렬 연산에 편리한 기능 제공
- 모든 원소는 같은 자료형만 가능

In [5]:
## numpy 데이터 만들기(나열하는 방식) => arange(데이터를 나열하는 함수) 사용
## 데이터를 나열한 후 2차원으로 바꾸기
## reshape를 쓸 때는 데이터 수와 일치되도록 행, 열의 수를 지정 필요->안그러면 오류 발생
import numpy as np # as : 별칭부여
a=np.arange(15) # 0~14까지 나열->1차원 데이터
print(a) # 1차원 데이터 반환
a=a.reshape(3,5) # reshape : 차원을 변경/ 3행 5열 데이터로 변경
print(a) # 2차원 데이터 반환

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [6]:
import numpy as np # as : 별칭부여
a=np.arange(15) # 0~14까지 나열->1차원 데이터
print(a) # 1차원 데이터 반환
a=a.reshape(3,5) # reshape : 차원을 변경/ 3행 5열 데이터로 변경
print(a) # 2차원 데이터 반환
print(type(a))
print(a.shape)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
<class 'numpy.ndarray'>
(3, 5)


In [7]:
print(type(a))
print(a.dtype)

<class 'numpy.ndarray'>
int32


In [8]:
print(a.ndim)

2


In [12]:
# print(dir(np))

In [15]:
import numpy as np
a=np.arange(15)
a=a.reshape(3,5,order='F')
print(a)

[[ 0  3  6  9 12]
 [ 1  4  7 10 13]
 [ 2  5  8 11 14]]


In [25]:
b=np.array([-1,2,5,-3,0,7,-9,4,-4,-7]) # List
print(type(b))
print(b)

<class 'numpy.ndarray'>
[-1  2  5 -3  0  7 -9  4 -4 -7]


In [24]:
t=(10,20,30,40,50) # tuple
print(type(t))
t=np.array(t)
print(type(t))

<class 'tuple'>
<class 'numpy.ndarray'>


In [26]:
s= {10,20,30,40,50} # set
print(type(s))
s=np.array(s)
print(type(s))

<class 'set'>
<class 'numpy.ndarray'>


In [36]:
# list에서 numpy로 변환한 변수 b 활용
b=np.array([-1,2,5,-3,0,7,-9,4,-4,-7])
print(b)

# abs : 절대값 구하는 함수
print(np.abs(b))

[-1  2  5 -3  0  7 -9  4 -4 -7]
[1 2 5 3 0 7 9 4 4 7]


In [33]:
print(b.shape)
print(b.ndim)
print(b.dtype)
print(b)

# print(help(np.arange))

(10,)
1
int32
[-1  2  5 -3  0  7 -9  4 -4 -7]


In [52]:
b=np.array([-1,2,5,-3,0,7,-9,4,-4,-7])
print(b)

# sqrt : 제곱근을 구하는 함수 -> 음수는 계산할 수 없기 때문에 "nan"으로 출력됨
print(np.sqrt(b))

[-1  2  5 -3  0  7 -9  4 -4 -7]
[       nan 1.41421356 2.23606798        nan 0.         2.64575131
        nan 2.                nan        nan]


C:\Users\ae397\AppData\Local\Temp\ipykernel_13324\4005714368.py:5: RuntimeWarning: invalid value encountered in sqrt
  print(np.sqrt(b))


In [50]:
# abs 함수와 함께 이용할 경우 음수를 양수로 바꿔서 제곱근 계산 가능
print(np.sqrt(np.abs(b)))

[1.         1.41421356 2.23606798 1.73205081 0.         2.64575131
 3.         2.         2.         2.64575131]


In [41]:
# square : 제곱을 구하는 함수
print(np.square(b))

[ 1  4 25  9  0 49 81 16 16 49]


In [44]:
# isnan : nan 값인지 여부를 묻는 함수
print(np.isnan(b))

[False False False False False False False False False False]


In [48]:
b=np.array([-1,2,5,-3,0,7,-9,4,-4,-7])
print(b)
print(np.isnan(b))

[-1  2  5 -3  0  7 -9  4 -4 -7]
[False False False False False False False False False False]


In [57]:
print(np.sum(b))  #합계
print(np.mean(b)) #평균
print(np.max(b)) #최댓값
print(np.min(b)) #최솟값
print(np.argmax(b)) # 최대값의 인덱스를 알려주는 함수
print(np.argmin(b)) #최소값의 인덱스를 알려주는 함수

-6
-0.6
7
-9
5
6


In [60]:
print(np.sort(b)) # 정렬, 오름차순
print(np.sort(b)[::-1]) #정렬, 내림차순/ 슬라이싱 활용

[-9 -7 -4 -3 -1  0  2  4  5  7]
[ 7  5  4  2  0 -1 -3 -4 -7 -9]


In [63]:
print(np.median(b)) #중간값

-0.5
