## Pandas

In [1]:
import pandas as pd
import numpy as np

### Series

In [8]:
s=pd.Series([1,2,3,4,5,6,7,8,9])  #Series 만들기
print(type(s))
print(s.index)  # index를 따로 지정하지 않으면 자동으로 숫자가 기재됨
print(s.dtype)
print(s)       # 출력 결과에서 왼쪽열이 index, 우측 열이 데이터

<class 'pandas.core.series.Series'>
RangeIndex(start=0, stop=9, step=1)
int64
0    1
1    2
2    3
3    4
4    5
5    6
6    7
7    8
8    9
dtype: int64


In [11]:
# 특정 인덱스명 부여
s.index=['A','B','C','D','E','F','G','H','I']
print(s)

A    1
B    2
C    3
D    4
E    5
F    6
G    7
H    8
I    9
dtype: int64


In [12]:
s=pd.Series([1,2,3,4,5,6,7,8,9],['A','B','C','D','E','F','G','H','I'])
print(s)

A    1
B    2
C    3
D    4
E    5
F    6
G    7
H    8
I    9
dtype: int64


In [18]:
print(s.index)  #index만 출력
print(s.values) #값만 출력
print(s['A']) #원하는 데이터만 출력
print(s.A)  #원하는 데이터만 출력

Index(['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I'], dtype='object')
[1 2 3 4 5 6 7 8 9]
1
1


In [20]:
## 슬라이싱 가능
print(s['A':'D'])  #직접 부여한 index 명 활용

A    1
B    2
C    3
D    4
dtype: int64


### Dictionary->Series
- Dictionary : 다른 언어의 Map, Json과 유사

In [26]:
d={'A':10,'D':20,'F':30,'H':40}
print(type(d))
for key,value in d.items() : # 딕셔너리 반복문, items로 key, value를 튜플 형식으로 꺼냄
    print(key,":",value)

print(d['A']) # 딕셔너리 특정 데이터 출력

<class 'dict'>
A : 10
D : 20
F : 30
H : 40
10


In [35]:
s=pd.Series(d)    #딕셔너리를 Series로 변경
print(s.index)
print(s.values)
print(s)
print(s['A'])  #특정 값 출력
print(s.A)     #특정 값 출력

print(s[0:3])  #딕셔너리는 슬라이싱이 불가, 하지만 Series로 변경 후에는 슬라이싱 가능
print(s['A':'F'])

Index(['A', 'D', 'F', 'H'], dtype='object')
[10 20 30 40]
A    10
D    20
F    30
H    40
dtype: int64
10
10
A    10
D    20
F    30
dtype: int64
A    10
D    20
F    30
dtype: int64


### DataFrame

In [38]:
# Dictionary->DataFrame
# 딕셔너리는 value 값에 list 등 여러 값 입력 가능
d={
    'name':['kim','lee','park','jung'],
    'age':[25,30,35,20],
    'tel':['1111-2222','2222-1111','3333-1111','2222-3333']
}
print(type(d))
print(d)

<class 'dict'>
{'name': ['kim', 'lee', 'park', 'jung'], 'age': [25, 30, 35, 20], 'tel': ['1111-2222', '2222-1111', '3333-1111', '2222-3333']}


In [40]:
df=pd.DataFrame(d)  #Dictionary->DataFrame
print(df)           #DataFrame 출력 시 테이블 형태로 출력 가능

   name  age        tel
0   kim   25  1111-2222
1   lee   30  2222-1111
2  park   35  3333-1111
3  jung   20  2222-3333


In [42]:
print(df.index)
print(df.columns)
print(df.values)

RangeIndex(start=0, stop=4, step=1)
Index(['name', 'age', 'tel'], dtype='object')
[['kim' 25 '1111-2222']
 ['lee' 30 '2222-1111']
 ['park' 35 '3333-1111']
 ['jung' 20 '2222-3333']]


In [45]:
# index와 colums에 특정 이름 부여 가능
df.index.name = 'Num'
df.columns.name='User'
print(df)

print(df.index)
print(df.columns)

User  name  age        tel
Num                       
0      kim   25  1111-2222
1      lee   30  2222-1111
2     park   35  3333-1111
3     jung   20  2222-3333
RangeIndex(start=0, stop=4, step=1, name='Num')
Index(['name', 'age', 'tel'], dtype='object', name='User')


In [47]:
# numpy->DataFrame
n=np.array(
    [['kim',20,'1111-2222'],
     ['lee',30,'2222-1111'],
     ['park',35,'3333-2222'],
     ['jung',25,'3333-1111']]
)
print(type(n))

<class 'numpy.ndarray'>


In [51]:
# numpy->DataFrame
df=pd.DataFrame(n)   #index, columns을 별도로 지정하지 않으면 숫자가 자동으로 배정됨
print(df)
print(df.index)
print(df.columns)

      0   1          2
0   kim  20  1111-2222
1   lee  30  2222-1111
2  park  35  3333-2222
3  jung  25  3333-1111
RangeIndex(start=0, stop=4, step=1)
RangeIndex(start=0, stop=3, step=1)


In [53]:
df.columns=['name','age','tel'] #columns 명 변경
df.index=['A','B','C','D']  #index 명 변경
print(df)
print(df.columns)
print(df.index)

   name age        tel
A   kim  20  1111-2222
B   lee  30  2222-1111
C  park  35  3333-2222
D  jung  25  3333-1111
Index(['name', 'age', 'tel'], dtype='object')
Index(['A', 'B', 'C', 'D'], dtype='object')


In [54]:
df=pd.DataFrame(n,columns=['name','age','tel'],index=['A','B','C','D'])
print(df)

   name age        tel
A   kim  20  1111-2222
B   lee  30  2222-1111
C  park  35  3333-2222
D  jung  25  3333-1111


In [56]:
# 데이터가 잘 들어있는지 확인하기 위해 사용하는 함수
# count : 빈 값이 있는지 확인
# unique : 다 다른 값이 들어있는지 확인하기 위함, 고윳값의 
#          (중복값이 있을 경우 개수가 작아짐, ex) 4 -> 4개의 데이터가 값이 달라!)
# top : 최빈값???
# freq : 최빈값의 빈도???
print(df.describe())

       name age        tel
count     4   4          4
unique    4   4          4
top     kim  20  1111-2222
freq      1   1          1


In [62]:
# 특정 columns만 출력
print(df['name'])  #'name'열만 출력, 한줄만 출력하기 때문에 series 타입으로 출력됨
print(type(df['name']))

A     kim
B     lee
C    park
D    jung
Name: name, dtype: object
<class 'pandas.core.series.Series'>


In [61]:
print(df[['name','tel']])  # 'name', 'tel'열만 출력

   name        tel
A   kim  1111-2222
B   lee  2222-1111
C  park  3333-2222
D  jung  3333-1111


In [71]:
# print(df['name'][2])  # 별도 index명이 부여된 상태에서 기본으로 부여되는 숫자로 조회
#                      ->조회 가능 but, 경고문 노출
print(df['name']['C'])
print(df['name'].C)
print(df['name']['B':'D'])

park
park
B     lee
C    park
D    jung
Name: name, dtype: object


In [73]:
print(df.name, df.age) # 특정 열들의 값을 따로따로 꺼내줘

A     kim
B     lee
C    park
D    jung
Name: name, dtype: object A    20
B    30
C    35
D    25
Name: age, dtype: object


In [74]:
print(df.name.C)

park


In [78]:
print(df[:][:])
print(df[:2][:1])  # 위에서 2줄을 꺼낸 후에 거기서 첫번째 1줄을 꺼내라

   name age        tel
A   kim  20  1111-2222
B   lee  30  2222-1111
C  park  35  3333-2222
D  jung  25  3333-1111
  name age        tel
A  kim  20  1111-2222


In [81]:
print(df[['name','tel']])
#print(df[[0,2]])   #이미 별도로 배정한 칼럼명이 있기 때문에 숫자로 조회 시 에러 발생
print(df)

   name        tel
A   kim  1111-2222
B   lee  2222-1111
C  park  3333-2222
D  jung  3333-1111
   name age        tel
A   kim  20  1111-2222
B   lee  30  2222-1111
C  park  35  3333-2222
D  jung  25  3333-1111


In [83]:
df['address']=['서울','수원','인천','안산']  #새로운 column 추가, 기존에 존재하는 열일 경우 값이 수정됨
print(df)

   name age        tel address
A   kim  20  1111-2222      서울
B   lee  30  2222-1111      수원
C  park  35  3333-2222      인천
D  jung  25  3333-1111      안산


In [93]:
df['adult']=df['age'].astype(np.int64)>30 #astype(np.int64):numpy에서 이용하는 형변환 변수
print(df)

   name age        tel address  adult
A   kim  30  1111-2222      서울  False
B   lee  30  2222-1111      수원  False
C  park  35  3333-2222      인천   True
D  jung  25  3333-1111      안산  False


In [94]:
df['age']['A']=20   #기존에 입력된 데이터 수정 가능
print(df)

   name age        tel address  adult
A   kim  20  1111-2222      서울  False
B   lee  30  2222-1111      수원  False
C  park  35  3333-2222      인천   True
D  jung  25  3333-1111      안산  False


C:\Users\ae397\AppData\Local\Temp\ipykernel_12408\1980487139.py:1: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df['age']['A']=20   #기존에 입력된 데이터 수정 가능
C:\Users\ae397\AppData\Local\Temp\ipykernel_12408\1980487139.py:1: SettingWithCopyWarning

In [95]:
del(df['adult'])   # 열 삭제 가능
print(df)

   name age        tel address
A   kim  20  1111-2222      서울
B   lee  30  2222-1111      수원
C  park  35  3333-2222      인천
D  jung  25  3333-1111      안산


In [99]:
# Series 정렬
s=pd.Series([10,40,50,20,70,60], index=['a','d','f','g','b','c'])
print(s)

a    10
d    40
f    50
g    20
b    70
c    60
dtype: int64


In [103]:
# index 정렬, 기본값=오름차순(trun)/ index 정렬 시 value도 따라서 변경됨
s=s.sort_index()
print(s)

a    10
b    70
c    60
d    40
f    50
g    20
dtype: int64


In [102]:
# index 정렬, 내림차순=False
s=s.sort_index(ascending=False)
print(s)

g    20
f    50
d    40
c    60
b    70
a    10
dtype: int64


In [105]:
# value 정렬 -> values 정렬에 따라 index 정렬도 바뀜
s=s.sort_values()
print(s)

a    10
g    20
d    40
f    50
c    60
b    70
dtype: int64


In [106]:
# value 정렬 -> values 정렬에 따라 index 정렬도 바뀜
s=s.sort_values(ascending=False)
print(s)

b    70
c    60
f    50
d    40
g    20
a    10
dtype: int64


In [143]:
# DataFrame 정렬
## DataFrame 데이터 생성
df=pd.DataFrame([[4,5,1,2],
                 [300,400,200,100],
                 [20,10,40,30]], index=['c','a','b'], columns=['D','C','A','B'])
print(df)

     D    C    A    B
c    4    5    1    2
a  300  400  200  100
b   20   10   40   30


In [117]:
# index로 정렬/ 별도 설정하지 않으면 오름차순
df=df.sort_index()
print(df)

     D    C    A    B
a  300  400  200  100
b   20   10   40   30
c    4    5    1    2


In [126]:
# index로 정렬/ axis 활용 가능 -> axis=0 : '행끼리'를 의미 => 행 기준으로 오름차순
df=df.sort_index(axis=0)
print(df)

     D    C    B    A
a  300  400  100  200
b   20   10   30   40
c    4    5    2    1


In [128]:
# index로 정렬/ 행 기준 내림차순(axis=0 생략 가능, 행 기준이기 때문)
df=df.sort_index(axis=0,ascending=False )
print(df)

     D    C    B    A
c    4    5    2    1
b   20   10   30   40
a  300  400  100  200


In [129]:
# column으로 정렬/ axis 활용 가능 -> axis=1 : '열끼리'를 의미 => 열 기준으로 오름차순
df=df.sort_index(axis=1)
print(df)

     A    B    C    D
c    1    2    5    4
b   40   30   10   20
a  200  100  400  300


In [132]:
# 열 기준으로 내림차순 정렬
df=df.sort_index(axis=1, ascending=False)
print(df)

     D    C    B    A
c    4    5    2    1
b   20   10   30   40
a  300  400  100  200


In [139]:
# value를 기준으로 정렬 / A열을 기준으로 정렬=>A열의 값들이 오름차순으로 정렬됨
print(df)

df=df.sort_values(by='A')
print(df)

     D    C    A    B
c    4    5    1    2
a  300  400  200  100
b   20   10   40   30
     D    C    A    B
c    4    5    1    2
b   20   10   40   30
a  300  400  200  100


In [145]:
# value를 기준으로 정렬 / A열을 기준으로 정렬=>A열의 값들이 내림차순으로 정렬됨
print(df)

df=df.sort_values(by='A', ascending=False)
print(df)

     D    C    A    B
c    4    5    1    2
a  300  400  200  100
b   20   10   40   30
     D    C    A    B
a  300  400  200  100
b   20   10   40   30
c    4    5    1    2


In [39]:
df=pd.DataFrame([[4,5,40,100],
                 [300,10,200,2],
                 [20,400,4,30]], index=['c','a','b'], columns=['D','C','A','B'])
print(df)

     D    C    A    B
c    4    5   40  100
a  300   10  200    2
b   20  400    4   30


In [3]:
# value를 기준으로 정렬 / A열을 기준으로 정렬=>A열의 값들이 오름차순으로 정렬됨
print(df)

df=df.sort_values(by='A')
print(df)

     D    C    A    B
c    4    5   40  100
a  300   10  200    2
b   20  400    4   30
     D    C    A    B
b   20  400    4   30
c    4    5   40  100
a  300   10  200    2


In [5]:
# value를 기준으로 정렬 / A열을 기준으로 정렬=>A열의 값들이 내림차순으로 정렬됨
print(df)

df=df.sort_values(by='A', ascending=False)
print(df)

     D    C    A    B
c    4    5   40  100
a  300   10  200    2
b   20  400    4   30
     D    C    A    B
a  300   10  200    2
c    4    5   40  100
b   20  400    4   30


In [13]:
print(df)

df=df.sort_values(by=['A', 'B']) # A로 먼저 정렬한 후 B로 정렬
print(df)

     D    C    A    B
c    4    5   40  100
a  300   10  200    2
b   20  400    4   30
     D    C    A    B
b   20  400    4   30
c    4    5   40  100
a  300   10  200    2


In [11]:
# 특정 인덱스 기준으로 정렬
print(df)

df=df.sort_values(by='b', axis=1)  #열끼리
print(df)

     A    D    B    C
c   40    4  100    5
a  200  300    2   10
b    4   20   30  400
     A    D    B    C
c   40    4  100    5
a  200  300    2   10
b    4   20   30  400


### 슬라이싱
- .iloc     정수 인덱스
- .loc      라벨 인덱스
- .ix       depercated

In [40]:
#list
m=[[1,2,3],[4,5,6],[7,8,9]]
print(m)
print(m[2][2])
print(m[:][:])
print(m[:2][:2])  # 앞에서 2개의 행 뽑은 후 그 중에서 2개의 행을 보여줘

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
9
[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
[[1, 2, 3], [4, 5, 6]]


In [41]:
# numpy
n=np.array(m)
print(n)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [42]:
print(n[2][2])
print(n[:][:])
print(n[:2][:2])
print(n[:2,:2])  # 앞에서 2개의 행 뽑은 후 그중 앞에서 2개의 열 추출

9
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]]
[[1 2]
 [4 5]]


In [43]:
# pandas
df=pd.DataFrame(n)
print(df)

   0  1  2
0  1  2  3
1  4  5  6
2  7  8  9


In [44]:
print(df[2][2])  # 현재 컬럼명을 따로 지정하지 않았기 때문에 숫자로 조회해도 조회됨
                 # (별도 컬럼이 지정되어 있을 경우 에러 발생)
print(df[:][:])
print(df[:2][:2])
# print(df[:2,:2])   # Numpy에서는 가능했으나 DataFrame에서는 에러 발생

9
   0  1  2
0  1  2  3
1  4  5  6
2  7  8  9
   0  1  2
0  1  2  3
1  4  5  6


In [62]:
 # 1~20까지 나열된 2차원 numpy를 dataframe으로 변경
df=pd.DataFrame(np.arange(1,21).reshape(5,4),columns=['A','B','C','D'])
print(df)

    A   B   C   D
0   1   2   3   4
1   5   6   7   8
2   9  10  11  12
3  13  14  15  16
4  17  18  19  20


In [63]:
# print(df[2][2]) ###현재 별도 컬럼명을 지정->오류 발생
print(df['C'][2])
print(df[['A','D']])
# print(df['A':'C'])  #에러 발생
# print(df[['A':'C']]) #에러 발생

11
    A   D
0   1   4
1   5   8
2   9  12
3  13  16
4  17  20


In [57]:
# 위와 같이 오류 발생하는 것들을 표현하기 위해 iloc(정수 인덱스만 가능) 사용
print(df.iloc[2][2])
print(df.iloc[2,2])
#print(df.iloc[2,'C'])   # iloc는 정수만 사용 가능 => 에러 발생
                         # 숫자말고 문자를 사용하고 싶을 경우 loc 사용

print(df.iloc[:2,:2])   # 슬라이싱 사용 가능
print(df.iloc[:3:2,:3:2]) # 0~2까지 행을 2개의 간격으로 조회 후 0~2까지 열을 2개의 간격으로 조회

11
11
   A  B
0  1  2
1  5  6
   A   C
0  1   3
2  9  11


C:\Users\ae397\AppData\Local\Temp\ipykernel_21576\38656942.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(df.iloc[2][2])


In [61]:
print(df.iloc[:2,:-1])
print(df.iloc[::-1,::-1])  # 간격에 -1 = 거꾸로 출력

   A  B  C
0  1  2  3
1  5  6  7
    D   C   B   A
4  20  19  18  17
3  16  15  14  13
2  12  11  10   9
1   8   7   6   5
0   4   3   2   1


In [66]:
# loc : 특정 컬럼명이 지정되었을 경우 컬럼명으로 조회
print(df)

    A   B   C   D
0   1   2   3   4
1   5   6   7   8
2   9  10  11  12
3  13  14  15  16
4  17  18  19  20


In [68]:
# print(df.loc[2,2])   # 특정 컬럼명이 지정된 상태->숫자로 조회할 경우 에러 발생
print(df.loc[2,'C'])   # 컬럼명으로 조회 시 정상적으로 조회 가능

11


In [74]:
print(df.loc[:2,:'C'])
print(df[:2])
print(df.loc[1:3,'B':'D'])
print(df.loc[:,'C'])   # 모든 행, C열만 조회
print(df.loc[:,['B','D']]) # 모든 행, B열과 D열 조회
print(df[['B','D']])  # 윗줄과 동일하게 B열과 D열 조회->BUT, 특정 행을 지정할 수 없음

   A   B   C
0  1   2   3
1  5   6   7
2  9  10  11
   A  B  C  D
0  1  2  3  4
1  5  6  7  8
    B   C   D
1   6   7   8
2  10  11  12
3  14  15  16
0     3
1     7
2    11
3    15
4    19
Name: C, dtype: int32
    B   D
0   2   4
1   6   8
2  10  12
3  14  16
4  18  20
    B   D
0   2   4
1   6   8
2  10  12
3  14  16
4  18  20


In [75]:
# 컬럼 추가
print(df)

    A   B   C   D
0   1   2   3   4
1   5   6   7   8
2   9  10  11  12
3  13  14  15  16
4  17  18  19  20


In [81]:
# 컬럼 추가
df['E']=[31,32,33,34,35]   # 컬럼 추가 가능
# df[5][:]=[90,91,92,93,94]  # 행 추가 불가능
print(df)

    A   B   C   D   E
0   1   2   3   4  31
1   5   6   7   8  32
2   9  10  11  12  33
3  13  14  15  16  34
4  17  18  19  20  35


In [83]:
# 컬럼 추가 - iloc 사용 => iloc의 경우 새로운 데이터 추가 불가!!!
## df.iloc[:,5]=[40,41,42,43,44]    # 에러 발생(컬럼 명이 기재되지 않았기 때문)
## df.iloc[5,:]=[90,91,92,93,94]    # 에러 발생
print(df)

IndexError: iloc cannot enlarge its target object

In [89]:
 # 1~20까지 나열된 2차원 numpy를 dataframe으로 변경
df=pd.DataFrame(np.arange(1,21).reshape(5,4),columns=['A','B','C','D'])
df['E']=[31,32,33,34,35]
print(df)

    A   B   C   D   E
0   1   2   3   4  31
1   5   6   7   8  32
2   9  10  11  12  33
3  13  14  15  16  34
4  17  18  19  20  35


In [90]:
# loc 행추가 가능
df.loc[5]=[90,91,92,93,94]
print(df)

    A   B   C   D   E
0   1   2   3   4  31
1   5   6   7   8  32
2   9  10  11  12  33
3  13  14  15  16  34
4  17  18  19  20  35
5  90  91  92  93  94


In [91]:
# loc 열추가 가능
df.loc[:,'F']=[40,41,42,43,44,45]
print(df)

    A   B   C   D   E   F
0   1   2   3   4  31  40
1   5   6   7   8  32  41
2   9  10  11  12  33  42
3  13  14  15  16  34  43
4  17  18  19  20  35  44
5  90  91  92  93  94  45


In [94]:
# 특정 데이터 수정 => 기존에 존재하는 컬럼명을 이용할 경우 값 수정
df.loc[0,'A']=99
print(df)

    A   B   C   D   E   F
0  99   2   3   4  31  40
1   5   6   7   8  32  41
2   9  10  11  12  33  42
3  13  14  15  16  34  43
4  17  18  19  20  35  44
5  90  91  92  93  94  45


In [96]:
# 특정 데이터 수정 => 기존에 존재하는 컬럼명을 이용할 경우 값 수정
df.loc[1,'A':'C']=[100,121,102]  # 1번 행의 A~C까지 열의 값 변경
print(df)

     A    B    C   D   E   F
0   99    2    3   4  31  40
1  100  121  102   8  32  41
2    9   10   11  12  33  42
3   13   14   15  16  34  43
4   17   18   19  20  35  44
5   90   91   92  93  94  45


In [98]:
# 특정 데이터 수정
df.loc[3,['A','C','E']]=[200,201,202]  # 3번 행의 A,C,E열의 값 변경
print(df)

     A    B    C   D    E   F
0   99    2    3   4   31  40
1  100  121  102   8   32  41
2    9   10   11  12   33  42
3  200   14  201  16  202  43
4   17   18   19  20   35  44
5   90   91   92  93   94  45


In [99]:
# 특정 열 지우기
print(df)

     A    B    C   D    E   F
0   99    2    3   4   31  40
1  100  121  102   8   32  41
2    9   10   11  12   33  42
3  200   14  201  16  202  43
4   17   18   19  20   35  44
5   90   91   92  93   94  45


In [100]:
# 특정 열 지우기
del(df['E'])
print(df)

     A    B    C   D   F
0   99    2    3   4  40
1  100  121  102   8  41
2    9   10   11  12  42
3  200   14  201  16  43
4   17   18   19  20  44
5   90   91   92  93  45


In [102]:
# drop 사용
df=df.drop('F',axis=1)   #특정 열 지우기, 기본값이 행이기 때문에 axis=1로 열 지정 필요
print(df)

     A    B    C   D
0   99    2    3   4
1  100  121  102   8
2    9   10   11  12
3  200   14  201  16
4   17   18   19  20
5   90   91   92  93


In [104]:
# drop 사용
df=df.drop(5,axis=0)   #특정 행 지우기, 기본값이 행이기 axis 생략 가능
print(df)

     A    B    C   D
0   99    2    3   4
1  100  121  102   8
2    9   10   11  12
3  200   14  201  16
4   17   18   19  20


### Boolean Indexing
- 논리값으로 인덱싱 가능

In [105]:
df=pd.DataFrame(
    [['kim',20,'1111-2222'],
     ['lee',30,'2222-1111'],
     ['park',35,'3333-2222'],
     ['jung',25,'3333-1111'],
     ['hong',40,'1111-3333']], columns=['name','age','tel']
)
print(df)

   name  age        tel
0   kim   20  1111-2222
1   lee   30  2222-1111
2  park   35  3333-2222
3  jung   25  3333-1111
4  hong   40  1111-3333


In [106]:
print(df.loc[3,'name'])

jung


In [109]:
# loc => Boolena Indexing 가능
# 조건에 맞는 데이터만 출력
print(df.loc[df['age']>30,['name','age']]) # age가 30보다 큰 행의 name과 age 출력

   name  age
2  park   35
4  hong   40


In [112]:
# loc => Boolena Indexing 가능
# 등호 사용 가능
print(df.loc[df['name']=='kim',:])  # name이 kim인 행의 모든 열 출력

  name  age        tel
0  kim   20  1111-2222


In [116]:
# loc => Boolena Indexing 가능
# 논리 연산자(and, or) 사용 가능

# 조건이 여러 개일 경우 소괄호로 정확히 구분해줘야 작동가능
# 아래 식에 age 조건에 소괄호 없을 경우 오류 발생
print(df.loc[(df['age']>20) & (df['age']<40), 'name':'tel'])

   name  age        tel
1   lee   30  2222-1111
2  park   35  3333-2222
3  jung   25  3333-1111


In [117]:
print(df.loc[[True,True,False,False,False],"name"])

0    kim
1    lee
Name: name, dtype: object


### 결측치 대체

In [154]:
df=pd.DataFrame(
    [['kim',20,'1111-2222'],
     ['lee',30,'2222-1111'],
     ['park',35,'3333-2222'],
     ['jung',25,'3333-1111'],
     ['hong',40,'1111-3333']], columns=['name','age','tel']
)
print(df)

   name  age        tel
0   kim   20  1111-2222
1   lee   30  2222-1111
2  park   35  3333-2222
3  jung   25  3333-1111
4  hong   40  1111-3333


In [155]:
df['address']=['서울',np.nan,np.nan,'수원',np.nan]   # 결측치 생성
print(df)

   name  age        tel address
0   kim   20  1111-2222      서울
1   lee   30  2222-1111     NaN
2  park   35  3333-2222     NaN
3  jung   25  3333-1111      수원
4  hong   40  1111-3333     NaN


In [130]:
# 결측치만 조회하기 => isnull() 함수 활용
print(df.loc[df['address'].isnull(),'address'])  #address가 NaN인 행의 address 출력

1    NaN
2    NaN
4    NaN
Name: address, dtype: object


In [139]:
# 여러 결측치
df['address']=['서울',np.nan,np.nan,'수원',None]   # 결측치 생성
print(df)

df.loc[df['address'].isnull(),'address'] # np.nan/None 상관없이 모든 결측치 조회

   name  age        tel address
0   kim   20  1111-2222      서울
1   lee   30  2222-1111     NaN
2  park   35  3333-2222     NaN
3  jung   25  3333-1111      수원
4  hong   40  1111-3333    None


1     NaN
2     NaN
4    None
Name: address, dtype: object

In [140]:
# 결측치를 특정 값으로 대체
df.loc[df['address'].isnull(),'address']='서울'
print(df)

   name  age        tel address
0   kim   20  1111-2222      서울
1   lee   30  2222-1111      서울
2  park   35  3333-2222      서울
3  jung   25  3333-1111      수원
4  hong   40  1111-3333      서울


In [142]:
# ' '이라는 결측치 생성
df.loc[::2,'address']=' '
print(df)

   name  age        tel address
0   kim   20  1111-2222        
1   lee   30  2222-1111      서울
2  park   35  3333-2222        
3  jung   25  3333-1111      수원
4  hong   40  1111-3333        


In [144]:
# 아무 것도 없는 문자열(' ')의 경우 등호로 골라낼 수 있음
# np.nan, None은 등호로 골라낼 수 없음(isnull 사용 필요)
df.loc[df['address']==' ', 'address']='서울'
print(df)

   name  age        tel address
0   kim   20  1111-2222      서울
1   lee   30  2222-1111      서울
2  park   35  3333-2222      서울
3  jung   25  3333-1111      수원
4  hong   40  1111-3333      서울


### 결측치 제거

In [156]:
# 결측치 생성
df.loc[::2,'tel']=np.nan  # 특정 부분만 비우기
df.loc[5,:]=[np.nan,np.nan,np.nan,np.nan]  #5행 전체 비우기
print(df)

   name   age        tel address
0   kim  20.0        NaN      서울
1   lee  30.0  2222-1111     NaN
2  park  35.0        NaN     NaN
3  jung  25.0  3333-1111      수원
4  hong  40.0        NaN     NaN
5   NaN   NaN        NaN     NaN


In [158]:
# dropna : not available인 경우 삭제
df.dropna(how='all', inplace=True)  #전체 다 NaN일 때만 삭제/inplace=True : 원본에 바로 적용
print(df)

   name  age        tel address
0   kim   20  1111-2222      서울
1   lee   30  2222-1111     NaN
2  park   35  3333-2222      수원
3  jung   25  3333-1111     NaN
4  hong   40  1111-3333     NaN


In [159]:
df.dropna(how='any', inplace=True) # 하나라도 NaN일 때 삭제
print(df)

   name  age        tel address
0   kim   20  1111-2222      서울
2  park   35  3333-2222      수원


In [183]:
df=pd.DataFrame(
    [['kim',20,'1111-2222','서울'],
     ['lee',30,'2222-1111',np.nan],
     ['park',35,'3333-2222','수원'],
     ['jung',25,'3333-1111',np.nan],
     ['hong',40,'1111-3333',np.nan]], columns=['name','age','tel','address']
)
df.loc[5,:]=[np.nan,np.nan,np.nan,np.nan]
print(df)

   name   age        tel address
0   kim  20.0  1111-2222      서울
1   lee  30.0  2222-1111     NaN
2  park  35.0  3333-2222      수원
3  jung  25.0  3333-1111     NaN
4  hong  40.0  1111-3333     NaN
5   NaN   NaN        NaN     NaN


In [184]:
# 새로운 값 추가
df['income']=[300, np.nan,400,500,np.nan,300]
print(df)

   name   age        tel address  income
0   kim  20.0  1111-2222      서울   300.0
1   lee  30.0  2222-1111     NaN     NaN
2  park  35.0  3333-2222      수원   400.0
3  jung  25.0  3333-1111     NaN   500.0
4  hong  40.0  1111-3333     NaN     NaN
5   NaN   NaN        NaN     NaN   300.0


In [185]:
# 특정 열에 있는 NaN 값만 다른 값으로 대체 필요 => fillna 사용
df.fillna({'address':'서울'},inplace=True)
print(df)

   name   age        tel address  income
0   kim  20.0  1111-2222      서울   300.0
1   lee  30.0  2222-1111      서울     NaN
2  park  35.0  3333-2222      수원   400.0
3  jung  25.0  3333-1111      서울   500.0
4  hong  40.0  1111-3333      서울     NaN
5   NaN   NaN        NaN      서울   300.0


In [186]:
# income의 결측치를 평균값으로 대체
df.fillna({'income':np.mean(df['income'])},inplace=True)
print(df)

   name   age        tel address  income
0   kim  20.0  1111-2222      서울   300.0
1   lee  30.0  2222-1111      서울   375.0
2  park  35.0  3333-2222      수원   400.0
3  jung  25.0  3333-1111      서울   500.0
4  hong  40.0  1111-3333      서울   375.0
5   NaN   NaN        NaN      서울   300.0


In [187]:
# 여러 행 삭제
df.drop([4,5],inplace=True)
print(df)

   name   age        tel address  income
0   kim  20.0  1111-2222      서울   300.0
1   lee  30.0  2222-1111      서울   375.0
2  park  35.0  3333-2222      수원   400.0
3  jung  25.0  3333-1111      서울   500.0


In [188]:
# 여러 열 삭제
df.drop(['address','income'], axis=1, inplace=True)
print(df)

   name   age        tel
0   kim  20.0  1111-2222
1   lee  30.0  2222-1111
2  park  35.0  3333-2222
3  jung  25.0  3333-1111


In [190]:
# 전치 행렬
print(df.transpose())

              0          1          2          3
name        kim        lee       park       jung
age        20.0       30.0       35.0       25.0
tel   1111-2222  2222-1111  3333-2222  3333-1111


### Pandas 함수

In [194]:
df=pd.DataFrame(
    [['kim',90,80,70],
     ['lee',45,np.nan,55],
     ['park',76,77,83],
     ['hong',np.nan,np.nan,77],
     ['kang',35,58,52],
     ['jang',np.nan,np.nan,np.nan]],columns=['name','kor','eng','mat']
)
print(df)

   name   kor   eng   mat
0   kim  90.0  80.0  70.0
1   lee  45.0   NaN  55.0
2  park  76.0  77.0  83.0
3  hong   NaN   NaN  77.0
4  kang  35.0  58.0  52.0
5  jang   NaN   NaN   NaN


In [196]:
# count
print(df.count())  # axis=0이 기본값(행끼리), 공백은 카운트하지 않음

name    6
kor     4
eng     3
mat     5
dtype: int64


In [199]:
print(df.count(axis=1)) # 열끼리 카운트

0    4
1    3
2    4
3    2
4    4
5    1
dtype: int64


In [200]:
# min 최소값
print(df.min())

name    hong
kor     35.0
eng     58.0
mat     52.0
dtype: object


In [204]:
# min : 공백 제외
# 현재 데이터의 경우 name은 최소값이 따로 없음->name 제외하고 최소값 비교
print(df.loc[:,'kor':'mat'].min())

kor    35.0
eng    58.0
mat    52.0
dtype: float64


In [205]:
# min : 공백 제외
# 현재 데이터의 경우 name은 최소값이 따로 없음->name 제외하고 "열끼리" 최소값 비교
print(df.loc[:,'kor':'mat'].min(axis=1))

0    70.0
1    45.0
2    76.0
3    77.0
4    35.0
5     NaN
dtype: float64


In [206]:
# max 최대값
print(df.max())

name    park
kor     90.0
eng     80.0
mat     83.0
dtype: object


In [208]:
# mean 평균값
# name의 경우 평균값을 구할 수 없으므로 name 제외하고 계산
print(df.loc[:,'kor':'mat'].mean())

kor    61.500000
eng    71.666667
mat    67.400000
dtype: float64


In [209]:
# mean 평균값
# name의 경우 평균값을 구할 수 없으므로 name 제외하고 "열끼리" 계산
print(df.loc[:,'kor':'mat'].mean(axis=1))

0    80.000000
1    50.000000
2    78.666667
3    77.000000
4    48.333333
5          NaN
dtype: float64


In [211]:
# sum
# 문자열인 name은 제외
print(df.loc[:,'kor':'mat'].sum())

kor    246.0
eng    215.0
mat    337.0
dtype: float64


In [213]:
# sum
# 문자열인 name은 제외 / 열끼리 계산
print(df.loc[:,'kor':'mat'].sum(axis=1))

0    240.0
1    100.0
2    236.0
3     77.0
4    145.0
5      0.0
dtype: float64


In [216]:
# median : 중간값
# 문자열인 name은 제외 / 짝수 개인 경우 중간값 2개 더해서 2로 나눔
print(df.loc[:,'kor':'mat'].median())

kor    60.5
eng    77.0
mat    70.0
dtype: float64


In [218]:
# cumsum : 누적합
# 문자열의 경우 합할 경우 글이 합쳐짐
print(df.cumsum())

                     name    kor    eng    mat
0                     kim   90.0   80.0   70.0
1                  kimlee  135.0    NaN  125.0
2              kimleepark  211.0  157.0  208.0
3          kimleeparkhong    NaN    NaN  285.0
4      kimleeparkhongkang  246.0  215.0  337.0
5  kimleeparkhongkangjang    NaN    NaN    NaN


In [219]:
# cumprod :누적곱
# 문자열 연산 불가 -> name 제외
print(df.loc[:,'kor':'mat'].cumprod())

          kor       eng           mat
0        90.0      80.0  7.000000e+01
1      4050.0       NaN  3.850000e+03
2    307800.0    6160.0  3.195500e+05
3         NaN       NaN  2.460535e+07
4  10773000.0  357280.0  1.279478e+09
5         NaN       NaN           NaN


In [220]:
# idxmax : 최대값의 인덱스
# idxmin : 최소값의 인덱스
print(df.idxmax())
print(df.idxmin())

name    2
kor     0
eng     0
mat     2
dtype: int64
name    3
kor     4
eng     4
mat     4
dtype: int64


In [221]:
# var : 분산
# std : 표준편차
print(df.loc[:,'kor':'mat'].var())
print(df.loc[:,'kor':'mat'].std())

kor    665.666667
eng    142.333333
mat    183.300000
dtype: float64
kor    25.800517
eng    11.930353
mat    13.538833
dtype: float64


In [229]:
# 점수 합계 열 추가
df['tot']=df.loc[:,'kor':'mat'].sum(axis=1)  # name을 제외한 값들을 더함
print(df)

   name   kor   eng   mat    tot       mean        avg
0   kim  90.0  80.0  70.0  240.0  80.000000  80.000000
1   lee  45.0   NaN  55.0  100.0  50.000000  50.000000
2  park  76.0  77.0  83.0  236.0  78.666667  78.666667
3  hong   NaN   NaN  77.0   77.0  77.000000  77.000000
4  kang  35.0  58.0  52.0  145.0  48.333333  48.333333
5  jang   NaN   NaN   NaN    0.0        NaN        NaN


In [228]:
# 점수 평균 열 추가
df['avg']=df.loc[:,'kor':'mat'].mean(axis=1)  # name을 제외한 값들의 평균
print(df)

   name   kor   eng   mat    tot       mean        avg
0   kim  90.0  80.0  70.0  240.0  80.000000  80.000000
1   lee  45.0   NaN  55.0  100.0  50.000000  50.000000
2  park  76.0  77.0  83.0  236.0  78.666667  78.666667
3  hong   NaN   NaN  77.0   77.0  77.000000  77.000000
4  kang  35.0  58.0  52.0  145.0  48.333333  48.333333
5  jang   NaN   NaN   NaN    0.0        NaN        NaN


In [233]:
df=df.drop('mean',axis=1)
print(df)

   name   kor   eng   mat    tot        avg
0   kim  90.0  80.0  70.0  240.0  80.000000
1   lee  45.0   NaN  55.0  100.0  50.000000
2  park  76.0  77.0  83.0  236.0  78.666667
3  hong   NaN   NaN  77.0   77.0  77.000000
4  kang  35.0  58.0  52.0  145.0  48.333333
5  jang   NaN   NaN   NaN    0.0        NaN


In [236]:
# corr : 상관관계
# 1=양의 상관관계, 0=상관관계가 낮다(없다), -1=음의 상관관계
print(df['kor'].corr(df['eng']))
print(df)

0.9926458576614517
   name   kor   eng   mat    tot        avg
0   kim  90.0  80.0  70.0  240.0  80.000000
1   lee  45.0   NaN  55.0  100.0  50.000000
2  park  76.0  77.0  83.0  236.0  78.666667
3  hong   NaN   NaN  77.0   77.0  77.000000
4  kang  35.0  58.0  52.0  145.0  48.333333
5  jang   NaN   NaN   NaN    0.0        NaN
